Ss 180
harvard-lts/jstor_aspace_oai_harvester pull request #9
Opened 2023-01-31 19:51 UTC by michael-lts

**Handle multiple sets**
* * *

**JIRA Ticket**: [(link)](https://jira.huit.harvard.edu/browse/SS-182)

* Additional jira: https://jira.huit.harvard.edu/browse/SS-181

# What does this Pull Request do?
iterates through multiple sets, using configuration file for set information

# How should this be tested?
Deploy to dev (done)
Locally, from project root, run > python3 test/invoke_task.py

# Test coverage
Yes/No: Are changes in this pull-request covered by:
- unit tests?
- integration tests? Partial, subsequent pr will handle testing of harvest

2023-01-31 22:29 UTC, cgoines approved these changes

2023-01-31 22:29 UTC, cgoines commented
int tests pass

2023-01-31 22:41 UTC, awoods requested changes

2023-01-31 22:41 UTC, awoods commented on app/jstor_harvester.py
> +                            f = open(harvestDir + opDir + "/" + item.header.identifier + ".xml", "w")
@michael-lts : here is where you should use `with`, i.e.
```
with open(harvestDir + opDir + "/" + item.header.identifier + ".xml", "w") as f:
...
```

2023-01-31 22:41 UTC, awoods commented on app/jstor_harvester.py
> +            # leave during development, actually pulling from config file
Please create a JIRA ticket for this and add a link to the ticket as a comment here.

2023-01-31 22:41 UTC, awoods commented on app/jstor_harvester.py
> +            #current_app.logger.debug("harvestconfig")
Can we remove this dead code?

2023-02-01 00:17 UTC, michael-lts commented on app/jstor_harvester.py
> +                            f = open(harvestDir + opDir + "/" + item.header.identifier + ".xml", "w")
I was planning on a full review of file openings for the components in the next iteration ...

2023-02-01 15:39 UTC, awoods approved these changes

2023-02-01 15:41 UTC, merged